#Base Setting
spring:
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  sql:
    init:
      platform: mysql
      mode: always

debug: false
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    site.moamoa.backend: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql: trace

---
# Local Setting
spring:
  config:
    activate:
      on-profile: local
  redis:
    host: ${local.redis.host}
    port: ${local.redis.port}
  datasource:
    url: ${local.mysql.url}
    username: ${local.mysql.username}
    password: ${local.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/login/oauth2/code/naver # 추후 클라이언트 redirect uri로 넘겨줌
            authorization-grant-type: authorization_code
            scope: email, profile_image, nickname
            client-name: Naver

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

jwt:
  secretKey: ${JWT_SECRET_KEY} # base64로 인코딩된 암호 키, HS512를 사용할 것이기 때문에, 512비트(64바이트) 이상이어야 함

  access:
    expiration: 3600000 # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: Authorization

  refresh:
    expiration: 1209600000 #  (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: Authorization-refresh

---
# Develop branch Setting
spring:
  config:
    activate:
      on-profile: develop
  redis:
    host: ${develop.redis.host}
    port: ${develop.redis.port}
  datasource:
    url: ${develop.mysql.url}
    username: ${develop.mysql.username}
    password: ${develop.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100

---

# Release branch Setting
spring:
  config:
    activate:
      on-profile: release
  redis:
    host: ${release.redis.host}
    port: ${release.redis.port}
  datasource:
    url: ${release.mysql.url}
    username: ${release.mysql.username}
    password: ${release.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100